/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Exercicio1;

public class App {
  

    public static void main(String[] args) {
        Pessoa pes = new Pessoa("Mathews", 1996, 1.70f);
        
        System.out.println("Os dados são: "+ pes.getInfo());
        System.out.println("A idade é de "+ pes.calcularIdade());
    }
}
